### ISSUE TITLE
Code from github does not compile in VS 2015

### ISSUE THREAD

**Issue by weltkante** [AArnott/CodeGeneration.Roslyn#10]
While trying to diagnose issue #8 I tried building my own version of the library so I can debug it, but it does not build cleanly at all in VS 2015 Update 3
- nuproj files don't load into the IDE (I did install the nuproj extension)
- the 'CodeGeneration.Roslyn' project references 'CodeGeneration.Roslyn.Attributes' in a way the IDE does not understand (yellow triangle on the item in the references subtree) but this does not seem to prevent it building
- the 'CodeGeneration.Roslyn' project makes use of the 'Validation' nuget package without referencing it
- the property pages of the two Attribute projects can't be opened: `An error occurred trying to load the page. Additional text found in JSON string after finishing deserializing object.` but they do compile

I suspect that this project is meant to be build on "Dev15" ? Anyways even if above issues can't be fixed it'd be great to have some info about building the code in the readme (like required VS version and dependencies on VS extensions)

**Comment by AArnott** [comment]
With #15 this builds with VS 2017. 

It also built with VS 2015 before, under the right conditions. But that's irrelevant now.
