### ISSUE TITLE
Apply to Assembly

### ISSUE THREAD

**Issue by romerod** [AArnott/CodeGeneration.Roslyn#105]
This is more a question than an issue, I hope you don't mind.

Is it possible to have code generation applied to the assembly, instead of a class or member?

**Comment by amis92** [comment]
Yes it is now possible, added in #67.

Just apply generator-triggering attribute to the `assembly` target instead of a class or member, e.g. `[assembly: MyCodeGeneration]`.

**Comment by romerod** [comment]
Thanks @amis92 , thats cool
