### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by MdmrBerlin** [AArnott/CodeGeneration.Roslyn#111]
Whitch status have this project?

Ready for use, alpha or beta?

I tryed the readme steps, downloadet the CodeGeneration.Roslyn.Walkthrough and another example.
There is actual no way to compile the projects or generate code, also the the example projects.
Maybe your documentation and example projects are out of date?

**Comment by amis92** [comment]
Hello, can you provide a little more context, e.g. what version of Visual Studio are you using?

I've updated the walkthrough (see PR: https://github.com/jaredthirsk/CodeGeneration.Roslyn.Walkthrough/pull/2) for 0.4.88 and it does work for me under VS2017 v15.9.5 (latest).

**Comment by jaredthirsk** [comment]
```
NuGet package restore finished.
Time Elapsed: 00:00:00.9341625
========== Finished ==========

NU1603: dotnet-codegen-netcoreapp2.2-[0.4.12, ) depends on dotnet-codegen (>= 0.4.12) but dotnet-codegen 0.4.12 was not found. An approximate best match of dotnet-codegen 0.4.37 was resolved.
NU1603: dotnet-codegen 0.4.37 depends on System.CommandLine (>= 0.1.0-e170407-3) but System.CommandLine 0.1.0-e170407-3 was not found. An approximate best match of System.CommandLine 1.0.0.1 was resolved.
NU1102: Unable to find package CodeGeneration.Roslyn with version (>= 1.0.0)
  - Found 22 version(s) in api.nuget.org [ Nearest version: 0.4.88 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
Time Elapsed: 00:00:09.3663684
========== Finished ==========

Time Elapsed: 00:00:00.2954482
========== Finished ==========

NuGet package restore failed. Please see Error List window for detailed warnings and errors.
Time Elapsed: 00:00:01.4044432
========== Finished ==========

Time Elapsed: 00:00:01.0255837
========== Finished ==========

```

**Comment by amis92** [comment]
Yes, it's true that the experience (when no SDK 2.0) is bad. There's the thing called `prefercliruntime` but it's undocumented and I do not know if this'll work or what it does :)

**Comment by jaredthirsk** [comment]
Can you just easily upgrade to a newer (non-EOL / non-obsolete) SDK?

**Comment by amis92** [comment]
(I'm not the owner of CG.R) Well, the thing is that we'd need to upgrade the tool for each new SDK version, which is just bad. Probably using `prefercliruntime` we'd "declare" ourselves compatible with the running/available SDK so that we could work for more targets. :<

**Comment by AArnott** [comment]
Thanks, @amis92. I have no objection to targeting a newer .NET Core if someone can send a PR to update that (and @amis92's new documentation to match :smile:).
