### ISSUE TITLE
Warning NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead.

### ISSUE THREAD

**Issue by amis92** [AArnott/CodeGeneration.Roslyn#116]

**Comment by amis92** [comment]
@AArnott There's a licensing dissonance - the `LICENSE.txt` is a MS-PL license, and yet the `stylecop.json` sets the license name as MIT.

Which is the actual license you want to use in this repo?

**Comment by AArnott** [comment]
Oh, good catch. MS-PL is what I intended.
