### ISSUE TITLE
How Packaging my code generator,with extensions CodeGeneration.Roslyn

### ISSUE THREAD

**Issue by hanxinimm** [AArnott/CodeGeneration.Roslyn#122]
![image](https://user-images.githubusercontent.com/13499426/54594871-7fa5b380-4a6c-11e9-92f6-997b5edf82d0.png)

if project reference it work better ,but when Packaging nuget, project install it, not work . 

i use .net core

**Comment by amis92** [comment]
Hi. I'm sorry, but I need some more details. What is your actual problem? What's working for you and what isn't?

**Comment by hanxinimm** [comment]
i create new project Hunter.Core.CodeGeneration with Implementation  RichGeneration, when i packing 
it for other code generation project, the  other project not work to generation code. i must be install CodeGeneration.Roslyn nuget, and copy Hunter.Core.CodeGeneration RichGeneration code to every code generation project, it work better!

**Comment by amis92** [comment]
@hanxinimm As I understand it, you pack your code generator into a NuGet and it doesn't work.

Have you followed https://github.com/AArnott/CodeGeneration.Roslyn#packaging-up-your-code-generator-for-others-use ?

**Comment by amis92** [comment]
Closed as deprecated
