### ISSUE TITLE
Is 0.5.13 an official release?  Upgrade breaks existing projects

### ISSUE THREAD

**Issue by ugumba** [AArnott/CodeGeneration.Roslyn#125]
0.5.13 is available on nuget, but upgrading breaks projects which have been working fine with 0.4.88.  "dotnet-codegen --version" fails.

**Comment by ugumba** [comment]
My apologies.  

I was actually missing DotNetCliToolReference in the csproj.  I had assumed it was not needed, since the nupkg's .props includes the line, but "dotnet restore" does not seem to look deeper than the .csproj when looking for these references.  Further, my "packages/.tools" already contained "dotnet-codegen/0.4.88", so I never needed to restore until I upgraded to 0.5.13.

Once this stuff works, it's brilliant - thanks!  Just wish dotnet codegen was quite a bit faster!  :-)

**Comment by amis92** [comment]
Thanks for self-follow-up :)

**Comment by bigdnf** [comment]
For me it is still breaking after update to 0.5.13. I also updated the versin in DotNetCliToolReference but have following error:

![codegen](https://user-images.githubusercontent.com/3872348/57198501-e1b26d80-6f73-11e9-9beb-1332a3261c1c.PNG)

**Comment by amis92** [comment]
@bigdnf if you could specify how exactly are you using the DotNetCliToolReference (in which file) it would be helpful. This DotNetCliTool feature is very error-prone and poorly supported via .NET Core SDK, as it turns out.

**Comment by bigdnf** [comment]
Like below - it worked with previous version.

![roslyn2](https://user-images.githubusercontent.com/3872348/57255800-44c80100-7055-11e9-962c-81ac2c621603.PNG)

**Comment by amis92** [comment]
@bigdnf is cloning https://github.com/jaredthirsk/CodeGeneration.Roslyn.Walkthrough and updating the version in `Walkthrough.Foo.csproj` working and building correctly? It's the simplest project possible. Works for me. Maybe there's an issue with .NET Core SDK of yours, or some other thing?

**Comment by bigdnf** [comment]
Ok I have it working - I'm not sure what exactly helped but for others with this problem I have
-	Clean nuget cache
-	Remove all .net core SDK
-	Remove .vs folder from project
-	Clean project
-	Rebuild

Now it works :)
