### ISSUE TITLE
Is StyleCop Beta dependency necessary

### ISSUE THREAD

**Issue by mwpowellhtx** [AArnott/CodeGeneration.Roslyn#129]
Hello,

@AArnott Is the [*StyleCop* ``1.1.1-beta.61``](http://nuget.org/packages/StyleCop.Analyzers/1.1.1-beta.61) dependency necessary? I am assuming it was the "latest" at one point, there have been several RC's and it is now in a stable [``1.1.118``](http://nuget.org/packages/StyleCop.Analyzers/1.1.118). Assuming a [``1.0.2``](http://nuget.org/packages/StyleCop.Analyzers/1.0.2) was not sufficient.

Thanks for clarifying! :+1: 

Cheers.

**Comment by amis92** [comment]
It's a development-only dependency, so I don't think it really matters. But yes, at a time it was "latest". For some future update it can probably be changed to the newest stable.

**Comment by mwpowellhtx** [comment]
Appreciate that, thank you.
