### ISSUE TITLE
What is Logger actually doing

### ISSUE THREAD

**Issue by mwpowellhtx** [AArnott/CodeGeneration.Roslyn#130]
Trying to grok the core [``Log``](/AArnott/CodeGeneration.Roslyn/blob/master/src/CodeGeneration.Roslyn/Logger.cs#L63) method. What is it actually doing? Basically splitting/reporting "lines" (loosely speaking) of potentially new-line or carriage-return-new-line delimited text? Why not simply use the [``String.Split``](http://docs.microsoft.com/en-us/dotnet/api/system.string.split#System_String_Split_System_String___System_StringSplitOptions_) using the [``RemoveEmptyEntries``](http://docs.microsoft.com/en-us/dotnet/api/system.stringsplitoptions)?

**Comment by amis92** [comment]
It might've been overcomplicated. My best guess is for performance reasons to minimize amount of `string` instances.

**Comment by AArnott** [comment]
Gah, I have no idea what it's doing. I deny any ownership of that. ;)

**Comment by mwpowellhtx** [comment]
Trying for it to behave like a ``Span`` before there was such a thing?

**Comment by LokiMidgard** [comment]
I think the initial version of the logger [was written by me](https://github.com/AArnott/CodeGeneration.Roslyn/commit/396d2e781e6b68dd46e66319843f3f627ad3957e). I think I just tried to allocate less strings.
