### ISSUE TITLE
Reasoning behind spanning CodeGeneration through the Engine assembly

### ISSUE THREAD

**Issue by mwpowellhtx** [AArnott/CodeGeneration.Roslyn#131]
Hello,

It appears as though [TransformationContext](/AArnott/CodeGeneration.Roslyn/blob/master/src/CodeGeneration.Roslyn/TransformationContext.cs) is really key to driving the whole code generation process. However, what I do not understand is why instantiation occurs in the [Engine](/AArnott/CodeGeneration.Roslyn/tree/master/src/CodeGeneration.Roslyn.Engine) assembly and not in the [CodeGeneration.Roslyn](/AArnott/CodeGeneration.Roslyn/tree/master/src/CodeGeneration.Roslyn)?

Thank you, cheers.

**Comment by amis92** [comment]
`CodeGeneration.Roslyn` is supposed to only contain an API interface required for implementation of generators.

Engine package is used by the Tool (`dotnet-codegen`) and contains an implementation of the process.

**Comment by mwpowellhtx** [comment]
Thank you for that. Appreciated.
