### ISSUE TITLE
What is ThisAssembly output

### ISSUE THREAD

**Issue by mwpowellhtx** [AArnott/CodeGeneration.Roslyn#133]
I'm searching for the terminology, it seems somewhat buried in the targets, but not for all targets. i could be wrong there. What is ``ThisAssembly``, how is it generated?

**Comment by amis92** [comment]
ThisAssembly is generated by Nerdbank.GitVersioning: https://github.com/AArnott/Nerdbank.GitVersioning

**Comment by AArnott** [comment]
This class is described here: https://github.com/AArnott/Nerdbank.GitVersioning/blob/c518c0306a3cdcf467871acdb6fd3430b662e632/doc/dotnet.md#L27
