### ISSUE TITLE
What is the purpose of `prefercliruntime'

### ISSUE THREAD

**Issue by mwpowellhtx** [AArnott/CodeGeneration.Roslyn#139]
I only see it referenced as ``Content`` in one place. Other than that I do not see any other references to it throughout the work space, for instance, and only [a couple](/AArnott/CodeGeneration.Roslyn/pull/85) of [passing references](/dotnet/docs/issues/7292) to it elsewhere. Thanks for any insights!

**Comment by AArnott** [comment]
It causes the dotnet cli to be willing to run the tool even if the runtime version doesn't match our target version.

**Comment by mwpowellhtx** [comment]
Appreciate the clarification, thanks.

**Comment by amis92** [comment]
For reference, it was introduced and "documented" in PR #85
