### ISSUE TITLE
Add support for MSBuild Core (and thus `dotnet build`)

### ISSUE THREAD

**Issue by AArnott** [AArnott/CodeGeneration.Roslyn#14]
Work in progress in the `netstandard` branch.

Blocked by:

* [x] https://github.com/NuGet/Home/issues/4655 Package dependencies are not suppressible when they come from a P2P reference

Remaining work:

* [x] Copy CoreCLR dependencies locally in the package.

**Comment by Liversage** [comment]
Will this fix https://github.com/AArnott/CodeGeneration.Roslyn/issues/12, i.e. enable this NuGet package to be used in Visual Studio 2017?

**Comment by AArnott** [comment]
I doubt it. And FWIW the currently released version works (for me) in VS 2017 just fine.

**Comment by Liversage** [comment]
@AArnott Thanks for the response. I tried to open my project using v0.1.57 in VS2017 today and I also experience https://github.com/AArnott/CodeGeneration.Roslyn/issues/12. I guess I will have to dig into the issue to understand what is causing the problem.
