### ISSUE TITLE
NuGet configuration packages direction

### ISSUE THREAD

**Issue by mwpowellhtx** [AArnott/CodeGeneration.Roslyn#149]
Hello,

Was the ``NuGet.Config`` entry, ``<add key="repositorypath" value="packages" />`` an effort to install the package dependencies, tooling, etc, in the local solution ``packages`` folder?

If so, I do not think that is the correct key. Try ``<add key="globalPackagesFolder" value="packages" />``.

Cheers.

**Comment by AArnott** [comment]
This entry is a carryover from packages.config days. It directed nuget to restore packages to a sibling to the src folder instead of under it.
We were not trying to redirect the global packages folder.
