### ISSUE TITLE
Upgrade build pipelines

### ISSUE THREAD

**Issue by amis92** [AArnott/CodeGeneration.Roslyn#153]
* Build using dotnet build on all platforms (prerequisite: use only x-plat TFMs)
* Drop passing around build results (from Windows to others)
* Build Sample solutions using just-built nugets

**Comment by AArnott** [comment]
> Drop passing around build results (from Windows to others)

This is actually a _feature_. We only push a package built on one platform. So testing a package on Linux that we built on Linux isn't testing what we propose to ship. It's most correct to test what we ship that Linux customers will use. 

For most repos building and testing on each OS is probably adequate. And as a bonus, adds a "test" that the repo can _build_ on these other platforms. But for this and a couple other repos I own, they do fancy enough things so as to be outside the typical happy path for .NET developers and I don't entirely trust the SDK to build exactly the same thing across platforms.
