### ISSUE TITLE
How to generate code during a build pipeline

### ISSUE THREAD

**Issue by mwpowellhtx** [AArnott/CodeGeneration.Roslyn#157]
I've got an internal code generator that I need to have engaged during the build pipeline. The project itself also carries with it several dependencies in its own right. Do I need to have the feeder generator project report its output to the consuming project for *CG* to take place? I take it that any references, project or package dependencies that it requires must also land there in order for *CGR* to properly activate an instance of the generator(s) themselves?

Illustrating, something like this:

```
project/package references -> code generator project(s) -> consumer project (i.e. where CG will actually happen)
```

All of which, `project/package references`, `code generator project(s)`, and so on, must land in the `consumer project` (or somewhere) where we identify the *code generator assets* to *CGR*.

Thanks...

**Comment by amis92** [comment]
If you're asking about this repository, the `dotnet-codegen` tool requires that folder containing generator's DLL (and all it's required dependencies) is included in `GeneratorAssemblySearchPaths` or `ReferencePath`.

https://github.com/AArnott/CodeGeneration.Roslyn/blob/master/src/CodeGeneration.Roslyn.BuildTime/build/CodeGeneration.Roslyn.BuildTime.targets#L32-L44
