### ISSUE TITLE
Fork with new experimental functional that allow full source code modification in compiler pipeline

### ISSUE THREAD

**Issue by GoldyD** [AArnott/CodeGeneration.Roslyn#159]
Hello All!

I create fork this project with new functional that allow full code modification in compiler pipeline  - add new piece of code, replace existing code to new one, remove existing code. 
Added capability to ordered transform one piece code with many generators defined on it.
AOP Welcome :)

Sample OrderedGeneratorsSolution solution added in samples folder.

Example of usage:
```csharp
    [TryCatchOrdered(ExecutionOrder = 1)]
    [DuplicateWithSuffixByNameOrdered("t", ExecutionOrder = 2)]    
    [RemoveOrdered(ExecutionOrder = 3)]
    public partial class Foo
    {
        [DuplicateWithSuffixByNameOrdered("t", ExecutionOrder = 1)]
        public object `Prop1;

        [DuplicateWithSuffixByNameOrdered("k", ExecutionOrder = 1)]
        public int? Prop2;

        public void Test()
        {
            var aa = 1;
            var dd = 3;
            var bb = 0;
            var cc = aa / bb;
        }
    }
```
Each attribute has ExecutionOrder property for order transform current node
Also added capability to transform fields or  properties.

After transformation current piece of code will be replaced to:
```csharp
    [TryCatchOrdered(ExecutionOrder = 1)]
    [DuplicateWithSuffixByNameOrdered("t", ExecutionOrder = 2)]
    [RemoveOrdered(ExecutionOrder = 3)]
    public partial class Foot
    {
        [DuplicateWithSuffixByNameOrdered("t", ExecutionOrder = 1)]
        public object Prop1;
        [DuplicateWithSuffixByNameOrdered("t", ExecutionOrder = 1)]
        public object Prop1t;
        [DuplicateWithSuffixByNameOrdered("k", ExecutionOrder = 1)]
        public int? Prop2;
        [DuplicateWithSuffixByNameOrdered("k", ExecutionOrder = 1)]
        public int? Prop2k;
        public void Test()
        {
            try
            {
                var aa = 1;
                var dd = 3;
                var bb = 0;
                var cc = aa / bb;
            }
            catch (Exception ex)
            {
            }
        }
    }
```

Transformations:
1) All methods wrapped to try catch block (in future generator may transformed for write all methods exceptions in log)
2) Created new copy of class Foo (after step 1) - Foot
3) Old class Foo will be removed

For create you own generation attribute - inherit this from  **OrderedCodeGenerationAttribute**.
For access full code transformation capability in generator - inherit this from **IRichCodeGenerator**, in **GenerateRichAsync** method assign **RichGenerationResult.Members** to list of **ChangeMember**, each member can do one of tree modification **AddMember**,   **ReplaceMember**, **RemoveMember**.

Not done yet:
 - speed optimization
 - partial regeneration when one part of partial entity (class, struct, interface) is changed.

Fork at:
[GoldyD](https://github.com/GoldyD/CodeGeneration.Roslyn)

**Comment by GoldyD** [comment]
My fork has same restriction as source project that can only generate new code.
In VS generation running in background, when base code class that has generator attributes will be changed and saved to disk.

- WPF design time builds (happen in the background and also rewrite stuff, do they work properly?)
   _Not tested  - I think it will be worked (you can try)_
-  intellisense code completion (in particular when editing code which is rewritten/replaced)
   _Worked_
-  debugging code which was rewritten (also editing while debugging)
   _Partially worked - show debugger generated method body, but editing while debugging not supported_

**Comment by AArnott** [comment]
I don't think I'd ever go for this because the line numbers reported in exceptions, crashes, etc would not line up with source code. You're welcome to continue the effort of course, but please do so on your own forum.
