### ISSUE TITLE
Intellisense problems when using this library

### ISSUE THREAD

**Issue by weltkante** [AArnott/CodeGeneration.Roslyn#16]
When using the 0.2.10 nuget package I don't get intellisense for the generated code in VS 2017. (copy/pasted the sample code on the front page in a new console project)

The project compiles but the `FooA` has no intellisense.

What is also odd is that the `DuplicateWithSuffix` attribute has no intellisense, even though it is in the referenced code assembly and not in generated code.

**Comment by M-Pixel** [comment]
I'm observing the same behavior. It worked the first time, but now none of the generated files (which I do see appear in `obj` under a subfolder named after the current target configuration) are referenced by the project.

**Comment by M-Pixel** [comment]
Unloading, then reloading the project caused the generated types to be included in my case, so maybe I observed a different issue than you. It still is an issue, but it's a usability inconvenience rather than a blocker.

**Comment by amis92** [comment]
Closing as deprecated. Project went through major refactor, documentation was updated.
