### ISSUE TITLE
[Proposal] Rename

### ISSUE THREAD

**Issue by amis92** [AArnott/CodeGeneration.Roslyn#164]
With #162 being a major rewrite, I thought it could be a good opportunity to mix it up a notch. We're considering breaking changes like #136 as well, which further "helps" 

`CodeGeneration.Roslyn` as a name has the following properties:
- ✔ direct reference to code generation area/feature
- ✔ direct reference to Roslyn which is a core component
- ❌ quite generic and not very recognizable/memorable
- ❌ hard to [search for on NuGet](https://www.nuget.org/packages?q=codegeneration.roslyn)

I propose to rename this project to a more unique and maybe catchy one. 😏🦄

My (currently only one) proposal:
- `Compilatron` - I've stumbled upon it playing Factorio (it's an in-campaign tutor-bot) and immediately thought about this project.
  - it's not taken: [GitHub](https://github.com/search?q=compilatron), [NuGet](https://www.nuget.org/packages?q=compilatron), [Google](https://www.google.com/search?q=compilatron) (almost exclusively links to Factorio).

I'm very open for different proposals though. Please share yours!

PS. @aarnott I'd like to ask you for opinion in this matter. Do you think renaming this project is sensible? Discussable? And as an owner: given an interesting enough proposal, would you consider agreeing to that?

**Comment by AArnott** [comment]
Hmmm... let me stew on it a little while.

**Comment by AArnott** [comment]
Let's close on #100 before considering a rename here. @amis92 can you drive that to a conclusion?

**Comment by amis92** [comment]
I've really wanted to not comment there as long as possible... ;)

**Comment by amis92** [comment]
@AArnott see https://github.com/AArnott/CodeGeneration.Roslyn/issues/100#issuecomment-533647426

**Comment by amis92** [comment]
Since Roslyn is deep in prototyping Source Generators, I think a rename in current timeframe is completely off the table.
