### ISSUE TITLE
Add list of projects using this

### ISSUE THREAD

**Issue by chinwobble** [AArnott/CodeGeneration.Roslyn#165]
Great project!

Do you think it would be good for adoption and demonstrability if you updated the docs with a section that lists all other consumers of this library?

Very similar to the fody version:
https://github.com/Fody/Home/blob/master/pages/addins.md

As a start you could add your other projects:

https://github.com/andrewlock/StronglyTypedId
https://github.com/AArnott/ImmutableObjectGraph
https://github.com/louthy/language-ext
https://github.com/AArnott/pinvoke

**Comment by chinwobble** [comment]
@AArnott  would you accept a PR updating the docs?

**Comment by Corniel** [comment]
Well we should add
* https://github.com/amis92/RecordGenerator

and hopefully (if I solve my issues):
* https://github.com/Qowaiv/qowaiv-codegenerator

**Comment by AArnott** [comment]
I've added the first one you suggested to [our wiki page](https://github.com/AArnott/CodeGeneration.Roslyn/wiki/Users), @Corniel. We can add the second one after you fill in a repo description and readme file so it's more consumable if folks click on it.
