### ISSUE TITLE
Causes frequent VS2019 16.3 freeze

### ISSUE THREAD

**Issue by ugumba** [AArnott/CodeGeneration.Roslyn#171]
In my solution with ~100 projects, ~20 use codegen 1.6.1 (netstandard20).  After upgrading to VS2019 16.3, we often experience freezes - not enough to be unusable, but annoying.  It can happen during a build, during live code analysis, or while trying to exit VS.

Killing a hanging "dotnet codegen --version" in Task Manager always resolves the freeze.

**Comment by AArnott** [comment]
What kinds of projects are you using? Is it a .csproj? And is it a .NET SDK style csproj or the older variety?

**Comment by ugumba** [comment]
The ones using codegen are all modern csproj, netstandard20. References by a few netcore30 (web/api apps).
I also use R#, which does a lot of MSBuild under the hood.
The "dotnet codegen --version" processes I kill are usually listed with only 30-40K memory in Task Manager. 
I almost never see the "VS is slow - reporting to MS" popup, so I guess it's hard to diagnose.
Anything I can do on my end?

**Comment by AArnott** [comment]
Great. I'm glad you're using the newest project file format. That means you're also using CPS which is our most modern project system, and the most likely to be able to address UI delays like what you're experiencing, if in fact fixing it in VS is required. But maybe there's a bug we can fix in CG.R. 

Can you us VS's "Report a Problem" command and select the performance tab and reproduce the problem? That will collect an ETL trace and send it to Microsoft. Then you'll get an email with a link to the issue you filed. If you send me that link, I'll look at the data and see what if anything we can do.

**Comment by ugumba** [comment]
Thanks!  Here's the issue: https://developercommunity.visualstudio.com/content/problem/801839/locked-by-dotnet-codegen-on-closing-solution.html

**Comment by AArnott** [comment]
Thanks, @ugumba. It looks like this isn't a `dotnet codegen` issue. Based on your trace, it's JetBrains that's really getting you down.

**Comment by ugumba** [comment]
I've uninstalled Resharper now, and I haven't seen the issue since - so it looks like you're correct. 
Thanks for your time!
