### ISSUE TITLE
MEF impact on build perf

### ISSUE THREAD

**Issue by AArnott** [AArnott/CodeGeneration.Roslyn#18]
MEF composition time. Each project (in the PInvoke project) repeats MEF discovery and composition instead of reusing results at least within the same process across projects. We should consider ways to reuse the work across projects -- possibly by making the AppDomain a static variable.

Although that risks locking DLLs after the build is finished if the nodes don't get unloaded.

**Comment by weltkante** [comment]
Is it possible to use the `Microsoft.VisualStudio.Composition` package for MEF composition? Not sure if the licensing allows using it for this scenario, but last time I looked it was able to persist the composition graph so it only needs to be recomputed if the assemblies actually changed.

Locking DLLs is certainly something I'd not want to happen to my generator assembly if they are in the same solution ...

**Comment by AArnott** [comment]
@weltkante That's an interesting idea. Caching the MEF graph would allow us to unload the AppDomain and release file locks. But the license for that assembly (which I wrote most of, BTW) doesn't permit use outside Visual Studio. 

But perhaps I can set up the AppDomain to enable shadow copying to avoid locking files (the way the VS test runner does).

**Comment by jasonmalinowski** [comment]
@AArnott: yep, easily. When you're creating any workspaces you can pass a HostServices type. The Microsoft.CodeAnalysis.Workspaces.Desktop assembly has a MefV1HostServices that implements this and just takes an v1 ExportProvider.

You can see us using VS MEF in Roslyn unit tests doing precisely this [here](https://github.com/dotnet/roslyn/blob/5f1130c8fe99e05222f35e6f9b9767de41642ed8/src/EditorFeatures/Test/Preview/PreviewWorkspaceTests.cs#L137).

**Comment by AArnott** [comment]
Thanks, @jasonmalinowski. @Pilchie also pointed out to me today that if instead of creating an `AdhocWorkspace` I simply create the `CSharpCompilation` directly, no MEF is used at all. I'm going to first try that route.

**Comment by AArnott** [comment]
Switching from `Workspace` to `CSharpCompilation` looks like it may work, but it involves a breaking change for my extensibility point because it means I have to pass around `SyntaxTree` instead of `Document`. Is that right, or can I create a `Document` for this without involving MEF?

**Comment by AArnott** [comment]
Never mind. It seems Workspaces are also required for `Formatter.Format` and `GetSemanticModelAsync`. So does that mean I'm locked into using MEF?

Also I am curious about something @jasonmalinowski said. How is it that my hosting MEF on Roslyn's behalf would require MEFv1 and v2, when Roslyn itself is only using MEFv2's library?

**Comment by jasonmalinowski** [comment]
@AArnott: you're right, I'm silly. If you're doing workspaces only you only need MEFv2. You only need MEFv1 if you're also doing editor stuff.

> It seems Workspaces are also required for Formatter.Format...

Ah, because we use that to discover the actual underlying formatter and the formatting rules. Ick. Not sure if we have a way around that today. If you're using this for autogenerated code we also have a method which lives at the compiler layer called "NormalizeWhitespace" that just blindly reformats to a given specified format. If you're using this for codegen you can just use that. The fancy formatter is intended for respecting user options and such, and is probably overkill for your case if you're not actually expecting users to look at or preserve the .cs file.

> and GetSemanticModelAsync...

If you're at the compiler layer only, you call Compilation.GetSemanticModel(syntaxTree). It's only async in the workspaces layer because we have to go get the tree first, which requires I/O.

**Comment by AArnott** [comment]
Thanks, @jasonmalinowski. I already use `NormalizeWhitespace()` on the entire CompilationUnit. I don't know what calling `Formatter.Format` buys me in addition to that. I wouldn't mind providing my own formatting options if there were an option to do that and avoid MEF. But ya, it looks like the formatting service is internal and only obtainable via MEF.
I'll see if I can just get by with the `NormalizeWhitespace()` call. I do expect users to step through the code in the debugger so it should be reasonably formatted.

And yes, I found the `GetSemanticModel` method, once I realized I needed to pass my `CSharpCompilation` along with the `SyntaxTree` as a tuple rather than just the `Document`. (duh me). Thanks.

**Comment by jasonmalinowski** [comment]
Were you calling NormalizeWhitespace and then Format? Because the latter Format might have not been doing anything. :smile: NormalizeWhitespace is what we sometimes call the "hammer of thor" formatter in that it just blindly formats to a well-known format, intended for code generation. It makes no attempt to preserve formats already there, it just goes to a sane format that should be fine for debugging.

**Comment by AArnott** [comment]
Then that sounds good.

I also conditionally run a Simplifier, but stopped doing that because it was *so painfully slow*. I have an active bug against roslyn on that, but so far it is getting punted each release. So it's turned off. So I guess I don't need to worry about the fact that that requires Document either.

**Comment by AArnott** [comment]
So yes, this works. NormalizeWhitespace does the job as you expected and I have no MEF and no Workspaces assemblies required to be deployed either. :)

**Comment by jasonmalinowski** [comment]
What did you want the Simplifier for? We generally only use that when we don't really know the environment we're generating code into. If you're controlling the whole file I wouldn't expect you're using it much if at all.

Your commit that tagged this bug looked good, once I got my mind out of thinking that "inputDocument" was a Document.

**Comment by jasonmalinowski** [comment]
(and thank you GitHub for not refreshing the issue as I had the tab open from a few hours ago)

**Comment by AArnott** [comment]
Thanks for reviewing the commit, @jasonmalinowski. 

I use simplifier because when I generate code into a new file, I fully-qualify all type references I emit. So the code looks quite verbose. But I also copy all using directives from the original file, so if I simplify the generated code, the types will reduce to what the user might actually write and it's more friendly to debug.

**Comment by AArnott** [comment]
BTW, this change to avoid MEF seems to have accelerated the PInvoke build by about 20%, which gave me the padding I needed to add netstandard1.1 and net20 targets to PInvoke and come out even. :)

**Comment by kzu** [comment]
This is very cool. Another trick I used was to share a Workspace only during a build, across all projects, by [registering a task object for the lifetime of the build](https://github.com/MobileEssentials/MSBuilder/blob/master/src/Roslyn/Roslyn/TaskExtensions.cs#L69-L86). 

It's what we in Xamarin to share the connection to the Mac across all iOS projects in a solution during a build.

**Comment by AArnott** [comment]
Wow. I had no idea MSBuild had that functionality. Very cool. I'm going to use this for other perf improvements.

**Comment by tg73** [comment]
It seems that `Microsoft.CodeAnalysis.Editing.SyntaxGenerator.GetGenerator(...)` requires a `Workspace`, or the closely-related `Document` or `Project`. Now that `Document` is no longer created and passed, what would be the best practice for successfully using `SyntaxGenerator`, bearing in mind the performance issues noted with the original implementation?

**Comment by AArnott** [comment]
I don't think I've used SyntaxGenerator. I just use SyntaxFactory.
