### ISSUE TITLE
[Infrastructure] Publishing requires signing nuget package

### ISSUE THREAD

**Issue by amis92** [AArnott/CodeGeneration.Roslyn#200]
🚨🚨🚨 @AArnott 🚨🚨🚨

It seems you've turned on package signing for your NuGet account, which this package is published to.

Can you fix that?

https://andrewarnott.visualstudio.com/OSS/_releaseProgress?_a=release-environment-logs&releaseId=118&environmentId=218

I guess the signing needs to be done on the deploy agent via some secrets I have no access to.

https://andrewarnott.visualstudio.com/OSS/_releaseDefinition?definitionId=2&_a=environments-editor-preview

**Comment by AArnott** [comment]
What? Gah! I didn't realize it would impact other packages. I'll get this fixed.

**Comment by AArnott** [comment]
Fixed. Try pushing to nuget.org again. (no certificate should be required).
