### ISSUE TITLE
MSBuild Task throws when P2P reference isn't built yet

### ISSUE THREAD

**Issue by AArnott** [AArnott/CodeGeneration.Roslyn#22]
This breaks the language service of the project in VS if the P2P isn't built.

The method that creates a metadata reference when creating the compilation project throws a FileNotFoundException and is reported in the VS error list. We should gracefully drop the reference when the file is missing.

**Comment by CarefreeCloud** [comment]
Hi,
Interested in this project. Trying to toy with v0.3 branch atm (To determine whether i could add this to my build process, while i'm not yet migrating to vs2017 and .net core SDK)
Any suggestions on how to workaround that issue? Seems to me like that is exactly what i bump into with my WPF .NET v4.6.2 project as test consumer

[build log.txt](https://github.com/AArnott/CodeGeneration.Roslyn/files/1200997/build.log.txt)

Solution with repro, if you think this is valid to investigate
[TestProject.zip](https://github.com/AArnott/CodeGeneration.Roslyn/files/1200999/TestProject.zip)

**Comment by amis92** [comment]
I don't reproduce this, or I don't really know how to. Anyway, doesn't look to be an issue any longer.
