### ISSUE TITLE
How does this relate to Source Generators from MS?

### ISSUE THREAD

**Issue by ugumba** [AArnott/CodeGeneration.Roslyn#229]
https://devblogs.microsoft.com/dotnet/introducing-c-source-generators

Will CodeGeneration.Roslyn be made redundant, or are there any important differences?

**Comment by amis92** [comment]
Source Generators will make this project redundant indeed.

There are differences, but not considerable enough to give this project any life support in future.

**Comment by garyng** [comment]
Why this makes me feel sad?

**Comment by AArnott** [comment]
I'm glad this project has been helpful to you, @garyng.

**Comment by LokiMidgard** [comment]
@AArnott  as you said [you don't want to maintain this anymor](https://github.com/AArnott/CodeGeneration.Roslyn/issues/237#issuecomment-741485572), maybe mention that in the README. I think you can also set something in github to mark it as no longer maintained.

**Comment by AArnott** [comment]
@amis92 Are you ready to archive this project as well? Or are you interested in maintaining it any longer?

**Comment by amis92** [comment]
I am ready to archive it.

![https://images.app.goo.gl/BpvYeLQGtcmFPRrp6]

Let's throw in a couple of links to the Source Generators into the Readme and call it done ☺️

**Comment by AArnott** [comment]
Let the record show that @amis92 really carried this project forward for the last 2+ years. Mega thanks!
