### ISSUE TITLE
Sample code does not produce new class in VS 2017

### ISSUE THREAD

**Issue by TenCoKaciStromy** [AArnott/CodeGeneration.Roslyn#23]
I tried the sample in VS 2017. The GenerateAsync method is called (the compilation is failing if exception is thrown) but no new class is created.

The generated class is not available from same project (console application) nor from unit test project.
All project are using .net framework 4.6.2.

**Comment by amis92** [comment]
Closing as deprecated. Project went through major refactor, documentation was updated.
