### ISSUE TITLE
.Net 5.0/3.1 support

### ISSUE THREAD

**Issue by max-ieremenko** [AArnott/CodeGeneration.Roslyn#237]
Hello @AArnott,

I use your CodeGeneration.Roslyn, however requirement for .net core sdk 2.1 is a little bit outdated.
Any releases for .net 5.0?

#229 >> Source Generators will make this project redundant indeed
Hmm..., indeed?

Source Generators from MS are too raw:
- external third party references is not [solved yet](https://github.com/dotnet/roslyn/discussions/47517#discussioncomment-6414)
- intellisense does not [work](https://github.com/dotnet/roslyn/issues/44093)

**Comment by AArnott** [comment]
I am not interested in maintaining this any more at this point. Source Generators do it better (it can generate code in the IDE even before the source files are saved), and will progress and fix their bugs much faster than this repo would and achieve a better integration with user flows than this repo could.

FWIW, my experience with source generators isn't perfect, but I don't see the errors you do. I have a source generator that has third party dependencies, and I see intellisense working.
