### ISSUE TITLE
Making it work on Omnisharp

### ISSUE THREAD

**Issue by masaeedu** [AArnott/CodeGeneration.Roslyn#27]
I am able to build .NET Standard 2.0 projects with code generation with the `dotnet` CLI tool, so I know that this works outside of Visual Studio. Unfortunately the Intellisense provided by the VS Code C# extension (which uses OmniSharp) doesn't seem to pick up on the generated code.

I don't really know whether this is possible, or how much work it would involve, but it would be really useful if this could be made to work with proper Intellisense.

**Comment by amis92** [comment]
I've verified in VSCode v1.33 and C#/Omnisharp v1.19 extension that IntelliSense provides suggestions based on generated files.
