### ISSUE TITLE
Allow to add custom usings in generated code.

### ISSUE THREAD

**Issue by bhugot** [AArnott/CodeGeneration.Roslyn#30]
Hello, I met a problem as i'm trying to generate code for NET3.5 and netstandard for Diagnostics.Tracing but in NET3.5 I have Microsoft.Diagnostics.Tracing and for netstandard it's System.Diagnostics.Tracing.

I don't know if there is a way so that the generator get the targetFramework or if I could add some using to my generated class.

**Comment by Pzixel** [comment]
@bhugot I'm currently using this workaroung:

```
var clientsNamespace = NamespaceDeclaration(ParseName("Clients"))
	.AddUsings(
		GetUsingDirectiveSyntax("System"),
		GetUsingDirectiveSyntax("System.Collections.Generic"),
		GetUsingDirectiveSyntax("System.Threading.Tasks"))
	.AddMembers(clientClass);

return Task.FromResult(List<MemberDeclarationSyntax>().Add(clientsNamespace));
```
It adds additional namespace but it's ok in my case. Probably, it helps you.

**Comment by bhugot** [comment]
@Pzixel Thanks found another way to do it for my case.

**Comment by Pzixel** [comment]
@bhugot then, please, share it? :) Maybe it would fit me better.

**Comment by bhugot** [comment]
I just use fullName for each class.

**Comment by amis92** [comment]
#80 resolved this.
