### ISSUE TITLE
Xml documentation comments from assembly references are not available

### ISSUE THREAD

**Issue by tg73** [AArnott/CodeGeneration.Roslyn#37]
All calls to `ISymbol.GetXmlDocumentationComment` for framework and other direct assembly references (ie, assemblies not being built) returns empty string. From what I can work out, a `DocumentationProvider` needs to be supplied when calling `MetadataReference.CreateFromFile`. More recent versions of `Microsoft.CodeAnalysis.Workspaces` dll expose `Microsoft.CodeAnalysis.XmlDocumentationProvider` publicly (1.3.2 does not, 2.2.0 does, I'm not sure where the change occurred), which then gives `XmlDocumentationProvider.CreateFromFile`. I've tried to apply the change myself, but updating the various 1.3.2 packages to 2.2.0 leads to a world of pain. Note that I'm using nuget packages 0.3.9 and the v0.3 branch.
```
var xmlDocPath = Path.ChangeExtension( p.ItemSpec, ".xml" );
return MetadataReference.CreateFromFile( p.ItemSpec, documentation: File.Exists( xmlDocPath ) ? XmlDocumentationProvider.CreateFromFile( xmlDocPath ) : null );
```

**Comment by amis92** [comment]
Closing as deprecated. Project went through major refactor, documentation was updated.
