### ISSUE TITLE
Document NuGet packaging steps

### ISSUE THREAD

**Issue by DamianReeves** [AArnott/CodeGeneration.Roslyn#4]
You refer to the steps of packaging everything up as being tedious. Could you please at least list out the general steps needed? 

My goal here is to adjust my NuGet packaging build script to correctly package up everything that is needed so that my code generator can be distributed via NuGet.

**Comment by AArnott** [comment]
I'd refer you to https://github.com/aarnott/immutableobjectgraph as a sample, but it's broken right now. (doh!)

**Comment by AArnott** [comment]
I'm improving the story here. Packaging will be easier, involve fewer dependencies, and actually fix ImmutableObjectGraph's master branch.

**Comment by DamianReeves** [comment]
Wonderful. Thanks
