### ISSUE TITLE
Missing real sample project using package not project

### ISSUE THREAD

**Issue by bhugot** [AArnott/CodeGeneration.Roslyn#41]
I think you should create another repo with a Sample in 3 part : 

1. CodeGenerator Lib
2. Attribute Lib
3. Test

**Comment by AArnott** [comment]
That's a good idea.

**Comment by Pzixel** [comment]
You can look at mine project until it's node because now I just have what do you need: a simple project that  consume `CodeGeneration.Roslyn` as a dependency: https://github.com/Pzixel/RemoteClient.Roslyn

**Comment by amis92** [comment]
The repo was actually created under here: https://github.com/jaredthirsk/CodeGeneration.Roslyn.Walkthrough
