### ISSUE TITLE
Error with dotnet-codegen

### ISSUE THREAD

**Issue by bhugot** [AArnott/CodeGeneration.Roslyn#42]
Hello,

I try to do a sample following your readme but I can't compile it. 

I got an error in
 Task "GenerateCodeFromAttributes"
         dotnet codegen 

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.CommandLine, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

**Comment by AArnott** [comment]
It looks like your package restore was incomplete. It looks like the README talks about this, but only in the context of packaging up your code generator which may not even apply to you. But the nuget.config change applies to everyone. Per the very end of the readme then, please add this nuget.config file to your repo:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="corefxlab" value="https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by bhugot** [comment]
The package for this lib is in my nuget cache and I followed your readme

**Comment by AArnott** [comment]
Are you sure your package cache has the 0.1.0.0 version? Or is it a 1.0 version? 
Also, please review your package restore logs for any warnings about pulling in a newer version than the one that was requested.

**Comment by bhugot** [comment]
I had the 0.1.0.0 in the same one you load in your project. I m off work I will check next monday

**Comment by AArnott** [comment]
No idea why it would fail then. Does `dotnet codegen` fail at the command line as well?

**Comment by bhugot** [comment]
Made it work, it was a problem with the dotnet sdk preview version I had. I updated it and it's working.

Thanks
