### ISSUE TITLE
Replacing method at compilation-time

### ISSUE THREAD

**Issue by CarefreeCloud** [AArnott/CodeGeneration.Roslyn#47]
Maybe I got it all wrong, but is it even possible to exclude attribute consumer MemberDeclarationSyntaxs from compilation?
So if I have a code generation-consumer method, I still have it with same identifier, but slightly changed at buildtime

**Comment by AArnott** [comment]
No. Code generation is limited to *adding* members/types, not replacing existing ones. That's something of a fundamental limitation of the overall system for several reasons -- not so much a limitation of this project.

**Comment by orellabac** [comment]
@AArnott  Why is it considered a limitation of the overall system? I have been working a weaver tool based on this same approach and it works for me.
I made some slight changes but in general borrows all the same concepts that you have here
