### ISSUE TITLE
Access CompilationGenerator properties from ICodeGenerator

### ISSUE THREAD

**Issue by amerkoleci** [AArnott/CodeGeneration.Roslyn#49]
Hi,
I would like to know if is possible t access to properties like IntermediateOutputDirectory?

I'm creating different file from cs using the ICodeGenerator logic.

**Comment by AArnott** [comment]
Not currently. I think if we wanted to support generating additional files we'd want to expose proper support for that rather than just expose the intermediate output directory, since this would feed into incremental build checks.
Do you need to control the name of the file being generated?

**Comment by amerkoleci** [comment]
I would like to parse the cs file and generate a shader hlsl file in the obj, intermediate dir, is this possible?

**Comment by amerkoleci** [comment]
I have something like this:

```
[ShaderProgram("HelloWorld")]
public class TestHelloWorldShaderProgram 
{
                [ShaderModule(ShaderStage.Vertex)]
		public PSInput VertexShader(VSInput input)
		{
                }
}
```

I already  generate with syntax walker the hlsl logic but at the moment I save the hlsl file to pass to fxc compiler under temp path.

**Comment by AArnott** [comment]
How do you influence the rest of the build to pick up your generated file?

**Comment by amerkoleci** [comment]
After ending the fxc compilation logic i read the compiled hlsl bytecode and generate class with roslyn with the bytecode as property

**Comment by AArnott** [comment]
So are you *reading* files from the intermediate output directory, or writing to it, or both?

**Comment by amerkoleci** [comment]
From the original cs file i generate hlsl under temp path, the invoke fxc compiler with generated hlsl then i use the roslyn method to generate new cs class with the bytecode embedded as field

**Comment by AArnott** [comment]
Why not use an embedded resource for storing the binary data?

**Comment by AArnott** [comment]
I know nothing about the Shader domain in case that wasn't obvious. So please forgive my ignorance.

**Comment by amerkoleci** [comment]
How can i generate embedded resource during ICodeGenerator logic?

**Comment by AArnott** [comment]
You can't. ICodeGenerator only lets you add compilation units (source files). But my question was more around trying to understand why your transform does C#->HSLS->fxc->C# and what value that adds to the developer. It seems odd to embed compiled binary code into C# source. When I add a binary file to an assembly, it's via embedded resources instead of as a `byte[]` usually.

**Comment by amerkoleci** [comment]
The value is that I can use C# as input language with all the power of c# and have compilation errors the transpile to hlsl or even different languages like GLSL or Metal

**Comment by AArnott** [comment]
Can you delete the intermediate files when you're done? Is there any value to leaving them around? Perhaps for incremental builds?

**Comment by amis92** [comment]
Supporting additional files in one or another form is not currently on this project's roadmap, and isn't expected in foreseeable future.
