### ISSUE TITLE
How do you change assembly level code?

### ISSUE THREAD

**Issue by DamianReeves** [AArnott/CodeGeneration.Roslyn#5]
I want to do something like the following: https://github.com/Fody/ModuleInit
Am I able to modify the <Module> class which does not directly allow me to place an attribute on it?

I'm trying to get this:

``` C#
using System;
internal class <Module>
{
	static <Module>()
	{
		ModuleInitializer.Initialize();
	}
}
```

**Comment by AArnott** [comment]
The code generator emits C# to be compiled with the project. It doesn't let you overcome C# language barriers such as specifying module initializers. So I don't think this project is a good fit to replace cecil.
Feel free to correct if I'm misunderstanding what you're asking for here.
