### ISSUE TITLE
How to debug and log

### ISSUE THREAD

**Issue by M-Pixel** [AArnott/CodeGeneration.Roslyn#51]
How does one

1. Attach a debugger to step through a generator?
2. Log from the generator, and view those logs?

**Comment by LokiMidgard** [comment]
I normally use `System.Diagnostics.Debugger.Break()`

**Comment by AArnott** [comment]
Yes, there's that or `Debugger.Launch()`.
Also during development I usually have a stub console project added to my solution that is configured to execute `msbuild /m:1 mysolution.sln` on F5, and I can just debug that to "build" and then debug into my code generator.
