### ISSUE TITLE
CodeGeneration.Roslyn.Attributes doesn't compile with VS2017. Dependencies / runtimes missing?

### ISSUE THREAD

**Issue by AdmiralSnyder** [AArnott/CodeGeneration.Roslyn#52]
I cannot compile the project CodeGeneration.Roslyn.Attributes in VS2017 (15.5.0 preview 2.0) as long as the entry portable-net45+win8+wpa81+wp8 is in its `<TargetFramework>` -node. are there any dependencies i am missing?

**Comment by AArnott** [comment]
hmm... you are running restore first, right?

**Comment by AdmiralSnyder** [comment]
i hadn't, i thought VS would do it, as it said in the status bar. but to be safe, i downloaded nuget.exe and ran nuget restore.
but the error persisted.
- then i cloned the repo again, opened it in VS2017 non-preview, and did the same (run nuget restore first). there it worked.
- then i cloned the repo again, opened it in VS2017 preview, ran nuget restore, but the error was there.
- then i cloned the repo once again, opened it in VS2017 non-preview, did not run nuget restore, and it worked.
-->so obviously, there is a problem with VS2017 preview; i'll investigate; maybe i am missing some installation component there, if not, i'll create an issue.
and, we learned, that the built-in nuget restore is sufficient; no manual restore is needed.
i think this resolves the issue.

**Comment by AArnott** [comment]
> if not, i'll create an issue.

Yes please. Thanks.

**Comment by AdmiralSnyder** [comment]
whoa, hours of trying and thinking and i found the problem:
seems they changed the collation (that's the correct word for the way letters are ordered, right?) from non-preview to preview:
if you change portable-net45+win8+wpa81+wp8 to portable-net45+win8+wp8+wpa81, it works. I haven't tested this with nonpreview vs yet. do you have an idea where to create that issue?

**Comment by AArnott** [comment]
I believe this is fixed by a33401b0fcf
