### ISSUE TITLE
generated artifacts should be put nested under the original file, instead of having them in the obj folder

### ISSUE THREAD

**Issue by AdmiralSnyder** [AArnott/CodeGeneration.Roslyn#55]
... just like the .designer.cs things and files that get created by TT
i think this makes it much more explorable

**Comment by AArnott** [comment]
But these aren't TT files. And whereas TT files are checked into source control and typically only updated within the IDE, this feature produces the files and build artifacts and they should *not* be checked into SCC. Generating these files into the source folder would be very confusing and certainly lead to folks accidentally checking the files in.
