### ISSUE TITLE
Sample app is not working.

### ISSUE THREAD

**Issue by roman-kozachenko** [AArnott/CodeGeneration.Roslyn#6]
Hello.
I was trying to use your library in small test application and failed.
What I was doing:
1. Created simple ConsoleApplication1.
2. Added new ClassLibrary1
3. Installed Nuget package CodeGeneration.Roslyn 0.1.57 to class library.
4. Added DuplicateWithSuffixAttribute and DuplicateWithSuffixGenerator classes from README.md to my class libraty.
(4.1.) Fixed a little DuplicateWithSuffixGenerator (IReadonlyCollection changed to SyntaxList).
5. Added Foo class to my ConsoleApplication1.
6. Added     [DuplicateWithSuffix("A")] attribute to Foo class.
7. Set Custom Tool property of Foo.cs file to `MsBuild:GenerateCodeFromAttributes`.
7. Added `var fooA = new FooA();` line to Main method.
8. Tried to build my test solution.

And unfortunately, ConsoleApplication1 is not building with error `error CS0246: The type or namespace name 'FooA' could not be found (are you missing a using directive or an assembly reference?)`. No other errors or warnings.
My guess is that GenerateCodeFromAttributes task is not launching. 
If I can provide any additional information, please let me know.

Thanks.

**Comment by DanTup** [comment]
Having the same issue; made some tweaks to get it compiling but seems like FooA is never created.

I have the codegen stuff in one project, my Foo (and code accessing FooA) in a second. Build tool is set as described in readme (this just seemed to be text which I pasted, wasn't an option to select?).

A small working sample project would be useful to compare to if it seems to work fine for you @Aarnott :)

**Comment by DanTup** [comment]
The previous version of the nupkg arms to have MSBuild targets etc that are missing from the latest (though it fails with MissingMethodExceptions).

Is something wrong with the latest nupkg? Is it supposed to have MSBuild targets and DLLs in tools?

**Comment by DanTup** [comment]
![codegen](https://cloud.githubusercontent.com/assets/1078012/17106011/861390ce-5281-11e6-89ca-f66d273f9dd7.jpg)

**Comment by AArnott** [comment]
Thanks for the report. It was just a bug in documentation. Check out the [fixes](https://github.com/AArnott/CodeGeneration.Roslyn/pull/7/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8).

**Comment by DanTup** [comment]
These are the same changes I made to get it compiling; but still doesn't seem to work. Could you attach a working test project that I could compare to?

**Comment by AArnott** [comment]
Yes: https://1drv.ms/u/s!Aj3kll8mDD0GgaXJVMVA6-Eqxl_yL88
