### ISSUE TITLE
State of System.CommandLine

### ISSUE THREAD

**Issue by LokiMidgard** [AArnott/CodeGeneration.Roslyn#63]
Are there any plans to change something on how the arguments are parsed.

If I see it correctly, the only reason the consumer of a generator written with this framework needs to put a `nuget.config` file in his project is because of how the arguments are parsed.

Looking at the repository, it does not seems like it will be out form beta (and on nuget) anytime soon.

I would like to have as less friction for the consumers of my libs as possible. Best case would be that only a nuget install is needed.

In my opinion the `nuget.config` could easily be avoided. 
+ Forking `System.CommandLine` and using the fork (until the original is out on nuget)
+ Using a different command line parser (don't know what's out there)
+ ~writing an own parser~

I think the first one would be a valid approach. Any thoughts on why this is a dumb idea?

**Comment by AArnott** [comment]
Not a bad idea. I'll check out options and keep this issue active to track.

**Comment by amis92** [comment]
It's officially archived: https://github.com/dotnet/corefxlab/pull/2245

So it'll never move out of MyGet. It's the final sign that this repo need to either copy the code over (it's under MIT so no prob) or just use another library completely.
