### ISSUE TITLE
Include of Microsoft.NETCore.App

### ISSUE THREAD

**Issue by LokiMidgard** [AArnott/CodeGeneration.Roslyn#64]
Is there a reason `Microsoft.NETCore.App` is explicitly referenced?

https://github.com/AArnott/CodeGeneration.Roslyn/blob/b889381999dd62ed03cc4051b07a2dd63dbedc88/src/CodeGeneration.Roslyn.Tool/CodeGeneration.Roslyn.Tool.csproj#L20

The compile issues warnings because of this because it is implicitly referenced.

**Comment by AArnott** [comment]
Ya, it's an annoying warning. But it does serve [a purpose](https://github.com/AArnott/CodeGeneration.Roslyn/commit/a1359b864bd8215dbc8d65b437d998977cca2f16): make the project work on Travis CI machines.
