### ISSUE TITLE
NuGet packages v0.4.37 have incorrect dependencies

### ISSUE THREAD

**Issue by amis92** [AArnott/CodeGeneration.Roslyn#68]
Something went wrong with building NuGet packages, because they all require "1.0.0" of the other project dependencies, namely:

* `dotnet-codegen` requires `CodeGeneration.Roslyn` v1.0.0
* `CodeGeneration.Roslyn` requires `CodeGeneration.Roslyn.Attributes` v1.0.0

All packages have package and assembly version set correctly to 0.4.37.

cc @AArnott @Pzixel

**Comment by Pzixel** [comment]
To prevent this in the future i'm working on referencing nuget packages that are packed during test instead of referencing projects directly. Brb when I'm done.

**Comment by Pzixel** [comment]
Good catch.

It's also interesting that my VS hangs when I'm trying to update this package

**Comment by Pzixel** [comment]
Created a PR: https://github.com/AArnott/Nerdbank.MSBuildExtension/pull/1 . Looking forward fix. When it get's merged we need syncronous update in this repo.  It also would be nice f @AArnott could just push it in master when MSBuildExtension gets updated.

**Comment by AArnott** [comment]
I don't see how this is related to https://github.com/AArnott/Nerdbank.MSBuildExtension/pull/1. That project doesn't determine the package versions/dependencies of its consumers like this project.

I can see from the CI build that this issue is already fixed. Probably by #62

**Comment by AArnott** [comment]
Published.
