### ISSUE TITLE
Documentation is not updated

### ISSUE THREAD

**Issue by bigdnf** [AArnott/CodeGeneration.Roslyn#97]
Main page contains only basic functionality but after digging into merged pull requests some features can be discovered. It would be nice that documentation would be updated to show all features of the library.

**Comment by amis92** [comment]
I'll take it on when I have some free time, unless someone else does it by that time. Might take me few weeks.

**Comment by AArnott** [comment]
Thanks, @amis92.

**Comment by amis92** [comment]
WIP: https://github.com/AArnott/CodeGeneration.Roslyn/wiki/Features

Please read through and suggest topics/improvements.

**Comment by amis92** [comment]
I've finished Features page and added a "How it works" page, which describes the process that happens during consumer build.

I think current state of wiki is good enough. I'll close this issue, but if someone feels a topic is missing, please say so.
